go.property("is_ended", false)
go.property("color", 0)
go.property("coords", vmath.vector3())

local function pick(self, touch_pos)
	if touch_pos.x >= (go.get_position().x - 32) and touch_pos.x <= (go.get_position().x + 32) then
		if touch_pos.y >= (go.get_position().y - 32) and touch_pos.y <= (go.get_position().y + 32) then
			return true
		end
	end
	return false
end 

function init(self)
	self.picked = false
end

function on_message(self, message_id, message, sender)
	if message_id == hash("on_pick_cell") then
		local pos = message.touch_pos
		if pick(self, pos) and self.picked == false then
			self.picked = true
			print("dsd")
			go.animate("#cell_sprite", "scale", go.PLAYBACK_ONCE_FORWARD, vmath.vector3(1.1, 1.1, 0), go.EASING_LINEAR, 0.1)
			msg.post(sender, "on_pick_cell", { cell_coordinates = self.coordinates })
		elseif pick(self, pos) == false and self.picked == true then
			self.picked = false
			go.animate("#cell_sprite", "scale", go.PLAYBACK_ONCE_FORWARD, vmath.vector3(1, 1, 0), go.EASING_LINEAR, 0.1)
		end
	elseif message_id == hash("on_release") then
		local pos = message.touch_pos
		if pick(self, pos) then
			self.picked = false
			go.animate("#cell_sprite", "scale", go.PLAYBACK_ONCE_FORWARD, vmath.vector3(1, 1, 0), go.EASING_LINEAR, 0.1)
		end
	elseif message_id == hash("on_start") then
		local pos = message.touch_pos
		if pick(self, pos) then
			self.picked = true
			go.animate("#cell_sprite", "scale", go.PLAYBACK_ONCE_FORWARD, vmath.vector3(1.1, 1.1, 0), go.EASING_LINEAR, 0.1)
		end
	end
end

function on_input(self, action_id, action)
end

function on_reload(self)
end

function final(self)
end

function update(self, dt)
end

function fixed_update(self, dt)
end