local colors_module = require("main.colors")
local cells_path = require("main.cells_path")

local function get_levels_settings(self)
	local levels_json = sys.load_resource("/res/json/levels.json")
	local table = json.decode(tostring(levels_json))
	return table["levels"]
end

local function clear_path(self, path)
	if path then
		for _, c in ipairs(path) do
			msg.post(c, "try_delete_pipe")
		end
		cells_path.clear_path(path)
		path = nil
	else 
		for _, c in ipairs(self.current_path) do
			msg.post(c, "try_delete_pipe")
		end
		cells_path.clear_path(self.current_path)
		self.current_path = nil
	end
end

local function is_valid(self, color, coords, sender)
--TITLE change color logic
	return color == self.current_color and 
		self.current_path[1] ~= sender and 
		math.abs(self.current_cell_coords.x - coords.x) + math.abs(self.current_cell_coords.y - coords.y) <= 1
--END
end

local function getn(table)
	local count = 0
	for _, val in pairs(table) do
		count = count + 1
	end
	return count
end

local function send_message_check_busy(self)
	local count = 0
	for key, value in pairs(self.cells) do
		count = count + 1
		local cell_url = msg.url(nil, value, "cell")
		msg.post(cell_url, "check_busy", {last = count == getn(self.cells)} )
	end
end

local function check_game_state(self) 
	if self.count_busy_cells == getn(self.cells) then
--TITLE Win Logic
print("WIN")
--END
	end
end


local function create_grid(self, count_in_row, count_in_columm, settings)
	math.randomseed(os.time())
	local idx_level = math.random(#settings)
	local settings_level = settings[idx_level]
	self.count_cells = count_in_columm * count_in_row
	local idx_cell = 0
	for i = 0, count_in_columm - 1 do
		for j = 0, count_in_row - 1 do
			idx_cell = idx_cell + 1
			local cell = factory.create("#cell_factory", 
				vmath.vector3(i * 70 + 100, j * 70 + 100, 0), 
				nil, 
				{ 
					is_ended = settings_level[idx_cell]["isEndPoint"], 
					color = settings_level[idx_cell]["endPointColor"],
					coords = vmath.vector3(i, j, 0)
				})
			self.cells[i.." "..j] = cell
			msg.post(cell, "add_cleat")
		end
	end
end

function init(self)
	msg.post(".", "acquire_input_focus")
	self.count_cells = 0
	self.cells = {}
	self.count_busy_cells = 0
	self.current_color = colors_module.NONE
	self.on_started = false
	self.current_cell_coords = vmath.vector3(-1, -1, -1)
	self.current_cell = nil
	self.prev_cell = nil
	self.prev_cell_coords = vmath.vector3(-1, -1, -1)
	self.current_path = nil
	self.last_touch_pos = nil
	local levels_settings = get_levels_settings(self)
	create_grid(self, 5, 5, levels_settings)
end

function final(self)
	msg.post(".", "release_input_focus")
end

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.pressed then
		for _, val in pairs(self.cells) do
			local cell_url = msg.url(nil, val, "cell")
			msg.post(cell_url, "on_start", { touch_pos = vmath.vector3(action.x, action.y, 0) })
		end
	elseif action_id == hash("touch") and action.released then
		if self.on_started then
			for _, val in pairs(self.cells) do
				local cell_url = msg.url(nil, val, "cell")
				msg.post(cell_url, "on_release", { touch_pos = vmath.vector3(action.x, action.y, 0) })
			end
			self.on_started = false
		end
	elseif action_id == hash("touch") then
		if self.on_started then
			for _, val in pairs(self.cells) do
				local cell_url = msg.url(nil, val, "cell")
				msg.post(cell_url, "on_pick_cell", { touch_pos = vmath.vector3(action.x, action.y, 0), vector = {x = 1, y = 2} })
			end
		end
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("ok_on_start") then
		if message.busy then
			local path = get_path_by_cell(sender)
			clear_path(self, path)
		else
			self.on_started = true
			self.current_cell_coords = message.coords
			self.current_cell = sender
			self.current_color = message.color;
			self.current_path = {}
			cells_pathes.add_path(self.current_path)
			msg.post(self.current_cell, "try_create_pipe", { color = message.color, vector = vmath.vector3(0, 0, 0)})
		end
	elseif message_id == hash("ok_on_pick") then
--TITLE change color logic
		if message.busy == true then
			msg.post(sender, "on_release", { touch_pos = message.touch_pos })
			self.on_started = false
		elseif math.abs(self.current_cell_coords.x - message.coords.x) + math.abs(self.current_cell_coords.y - message.coords.y) > 1 then
			msg.post(sender, "on_release", { touch_pos = message.touch_pos })
			self.on_started = false
		elseif message.is_ended == true and message.color ~= self.current_color then
			msg.post(sender, "on_release", { touch_pos = message.touch_pos })
			self.on_started = false
		else
--END
			self.prev_cell_coords = self.current_cell_coords
			self.current_cell_coords = message.coords
			self.prev_cell = self.current_cell
			self.current_cell = sender
			msg.post(self.prev_cell, "update_pipe", { vector = vmath.vector3(self.current_cell_coords.x - self.prev_cell_coords.x, 
			self.current_cell_coords.y - self.prev_cell_coords.y, 0)})
			msg.post(sender, "try_create_pipe", { color = self.current_color, 
				vector = vmath.vector3(self.current_cell_coords.x - self.prev_cell_coords.x, 
				self.current_cell_coords.y - self.prev_cell_coords.y, 0)})
		end
	elseif message_id == hash("ok_on_release") then
		if is_valid(self, message.color, message.coords, sender) then
			send_message_check_busy(self)
		else
			clear_path(self)
		end
		self.current_cell_coords = vmath.vector3(-1, -1, -1)
		self.prev_cell_coords = vmath.vector3(-1, -1, -1)
		self.current_color = colors_module.NONE
	end

	if message_id == hash("add_cell_to_path") then
		cells_path.try_add_cell(sender)
	end

	if message_id == hash("return_path_by_cell") then
		local deleted_cells_index = cells_pathes.return_by_cell(sender)[2]
		local path = cells_pathes.return_by_cell(sender)[1]
		for _, value in ipairs(deleted_cells_index) do
			msg.post(path[value], "try_delete_pipe")
		end
	end

	if message_id == hash("answer_is_busy") then
		if message.busy then
			self.count_busy_cells = self.count_busy_cells + 1
		end

		if message.last then
			check_game_state(self)
			self.count_busy_cells = 0
		end
	end
end

function on_reload(self)
end

function update(self, dt)
end

function fixed_update(self, dt)
end