local colors_module = require("main.colors")
local cells_path = require("main.cells_path")

local function get_levels_settings(self)
	local levels_json = sys.load_resource("/res/json/levels.json")
	local table = json.decode(tostring(levels_json))
	return table["levels"]
end

local function clear_path(self)
end

local function is_valid(path)
end

local function create_grid(self, count_in_row, count_in_columm, settings)
	local idx_level = math.random(#settings)
	local settings_level = settings[idx_level]
	self.count_cells = count_in_columm * count_in_row
	local idx_cell = 0
	for i = 0, count_in_columm - 1 do
		for j = 0, count_in_row - 1 do
			idx_cell = idx_cell + 1
			local cell = factory.create("#cell_factory", 
				vmath.vector3(i * 70 + 100, j * 70 + 100, 0), 
				nil, 
				{ 
					is_ended = settings_level[idx_cell]["isEndPoint"], 
					color = settings_level[idx_cell]["endPointColor"],
					coords = vmath.vector3(i, j, 0)
				})
			self.cells[i.." "..j] = cell
			msg.post(cell, "add_cleat")
		end
	end
end

function init(self)
	msg.post(".", "acquire_input_focus")
	self.count_cells = 0
	self.cells = {}
	self.current_color = colors_module.NONE
	self.on_started = false
	self.current_cell_coords = vmath.vector3(-1, -1, -1)
	self.current_cell = nil
	self.prev_cell = nil
	self.prev_cell_coords = vmath.vector3(-1, -1, -1)
	self.current_path = {}
	local levels_settings = get_levels_settings(self)
	create_grid(self, 5, 5, levels_settings)
end

function final(self)
	msg.post(".", "release_input_focus")
end

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.pressed then
		for _, val in pairs(self.cells) do
			local cell_url = msg.url(nil, val, "cell")
			msg.post(cell_url, "on_start", { touch_pos = vmath.vector3(action.x, action.y, 0) })
		end
	elseif action_id == hash("touch") and action.released then
		if self.on_started then
			for _, val in pairs(self.cells) do
				local cell_url = msg.url(nil, val, "cell")
				msg.post(cell_url, "on_release", { touch_pos = vmath.vector3(action.x, action.y, 0) })
			end
			self.on_started = false
		end
	elseif action_id == hash("touch") then
		if self.on_started then
			for _, val in pairs(self.cells) do
				local cell_url = msg.url(nil, val, "cell")
				msg.post(cell_url, "on_pick_cell", { touch_pos = vmath.vector3(action.x, action.y, 0), vector = {x = 1, y = 2} })
			end
		end
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("ok_on_start") then
		self.on_started = true
		self.current_cell_coords = message.coords
		self.current_cell = sender
		self.current_color = message.color;
		msg.post(self.current_cell, "try_create_pipe", { color = message.color, vector = vmath.vector3()})
	elseif message_id == hash("ok_on_pick") then
		self.prev_cell_coords = self.current_cell_coords
		self.current_cell_coords = message.coords
		self.prev_cell = self.current_cell
		self.current_cell = sender
		msg.post(self.prev_cell, "update_pipe", { vector = { x = nil, y = nil }})
		msg.post(sender, "try_create_pipe", { color = self.current_color, vector = vmath.vector3()})
	elseif message_id == hash("ok_on_release") then
		self.current_color = colors_module.NONE
		self.current_cell_coords = vmath.vector3(-1, -1, -1)
		self.prev_cell_coords = vmath.vector3(-1, -1, -1)
		if is_valid(self.current_path) then
			
		else
			clear_path(self)
		end
	end
end

function on_reload(self)
end

function update(self, dt)
end

function fixed_update(self, dt)
end