function init(self)
	msg.post(".", "acquire_input_focus")
end

function final(self)
	msg.post(".", "release_input_focus")
end

function update(self, dt)
end

function on_message(self, message_id, message, sender)
end

local function return_size(self, node)
	gui.animate(node, "scale", vmath.vector3(1, 1, 0), gui.EASING_LINEAR, 0.1)
end

local function start_click_animation(self, node)
	gui.animate(node, "scale", vmath.vector3(1.2, 1.2, 0), gui.EASING_LINEAR, 0.1, 0, return_size)
end

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.pressed then
		local reset = gui.get_node("reset")
		local exit = gui.get_node("exit")
		if gui.pick_node(exit, action.x, action.y) then
			msg.post("/grid#grid", "exit")
			start_click_animation(self, exit)
		end
		if gui.pick_node(reset, action.x, action.y) then
			msg.post("/grid#grid", "reset")
			start_click_animation(self, reset)
		end
	end
end

function on_reload(self)
end
